imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

mink:
    base_url:   http://m.local/web/app_test.php
    sahi:
        host:     m.local
    show_cmd:   google-chrome %%s
    #default_session: sahi
    default_session: symfony
behat: ~