#CordovaPhpSpecBundle:
#    resource: "@CordovaPhpSpecBundle/Resources/config/routing.xml"
#    prefix:   /

CordovaFormModelBundle:
    resource: "@CordovaFormModelBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

AcmePizzaBundle:
    resource: "@AcmePizzaBundle/Controller/"
    type:     annotation
    prefix:   /acme-pizza
